# Generated by Django 5.0.6 on 2024-06-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('post_type', models.TextField(blank=True, null=True)),
                ('post_type_format', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_strength', models.FloatField()),
                ('post_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.post')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedPost',
            fields=[
                ('recommendedPost_id', models.AutoField(primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField(blank=True, null=True)),
                ('content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.post')),
            ],
        ),
    ]
