# Generated by Django 5.0.6 on 2024-06-28 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.TextField()),
                ('post_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_Recommend',
            fields=[
                ('recommendedPost_id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test_Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_strength', models.FloatField()),
                ('post_content_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendation.test_post')),
            ],
        ),
    ]
