# Generated by Django 5.0.6 on 2024-06-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_test_post_test_recommend_test_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_interaction',
            name='post_content_id',
            field=models.TextField(),
        ),
    ]
